// This file is auto-generated by scripts/write-build-info.cjs
// Do not edit manually.

export const BUILD_GIT_SHA = "b796215";
export const BUILD_GIT_BRANCH = "main";
export const BUILD_TIME_ISO = "2026-04-17T08:25:23.205Z";
