// This file is auto-generated by scripts/write-build-info.cjs
// Do not edit manually.

export const BUILD_GIT_SHA = "4057395";
export const BUILD_GIT_BRANCH = "main";
export const BUILD_TIME_ISO = "2026-06-18T13:04:24.473Z";
