// This file is auto-generated by scripts/write-build-info.cjs
// Do not edit manually.

export const BUILD_GIT_SHA = "861fc8c";
export const BUILD_GIT_BRANCH = "main";
export const BUILD_TIME_ISO = "2026-06-07T04:51:23.021Z";
